---
- when: openshift_project_request_template_manage
  block:
    - name: Create temp file for template
      command: mktemp /tmp/openshift-ansible-XXXXXX.yaml
      register: mktemp
      changed_when: False

    - name: Generate default project template
      shell: |
        {{ openshift.common.client_binary | quote }} \
          --config {{ openshift.common.config_base | quote }}/master/admin.kubeconfig \
          --output yaml \
          adm create-bootstrap-project-template \
          --name {{ openshift_project_request_template_name | quote }} \
          > {{ mktemp.stdout | quote }}

    - name: Apply template modifications
      yedit:
        state: present
        src: "{{ mktemp.stdout }}"
        edits: "{{ openshift_project_request_template_edits }}"
      when: "openshift_project_request_template_edits | default({}) | length > 0"

    - name: Create or update project request template
      command: |
        {{ openshift.common.client_binary }} \
          --config {{ openshift.common.config_base }}/master/admin.kubeconfig \
          --namespace {{ openshift_project_request_template_namespace | quote }} \
          apply --filename {{ mktemp.stdout }}

    - name: Delete temp file
      file:
        name: "{{ mktemp.stdout }}"
        state: absent
      changed_when: False
