---
- name: Gather Master Facts
  hosts: oo_masters
  roles:
  - role: openshift_master_facts

- name: Create OpenShift certificates for master hosts
  hosts: oo_masters_to_config
  roles:
  - role: openshift_named_certificates
  - role: openshift_ca
  - role: openshift_master_certificates
