---
# defaults file for openshift_prometheus
openshift_prometheus_state: present

openshift_prometheus_namespace: openshift-metrics

openshift_prometheus_node_selector: {"region":"infra"}

# additional prometheus rules file
openshift_prometheus_additional_rules_file: null

# storage
# One of ['emptydir', 'pvc']
openshift_prometheus_storage_type: "emptydir"
openshift_prometheus_pvc_name: prometheus
openshift_prometheus_pvc_size: "{{ openshift_prometheus_storage_volume_size | default('10Gi') }}"
openshift_prometheus_pvc_access_modes: [ReadWriteOnce]
openshift_prometheus_pvc_pv_selector: "{{ openshift_prometheus_storage_labels | default({}) }}"
openshift_prometheus_sc_name: "{{ openshift_prometheus_storage_class | default(None) }}"

# One of ['emptydir', 'pvc']
openshift_prometheus_alertmanager_storage_type: "emptydir"
openshift_prometheus_alertmanager_pvc_name: prometheus-alertmanager
openshift_prometheus_alertmanager_pvc_size: "{{ openshift_prometheus_alertmanager_storage_volume_size | default('10Gi') }}"
openshift_prometheus_alertmanager_pvc_access_modes: [ReadWriteOnce]
openshift_prometheus_alertmanager_pvc_pv_selector: "{{ openshift_prometheus_alertmanager_storage_labels | default({}) }}"
openshift_prometheus_alertmanager_sc_name: "{{ openshift_prometheus_alertmanager_storage_class | default(None) }}"

# One of ['emptydir', 'pvc']
openshift_prometheus_alertbuffer_storage_type: "emptydir"
openshift_prometheus_alertbuffer_pvc_name: prometheus-alertbuffer
openshift_prometheus_alertbuffer_pvc_size: "{{ openshift_prometheus_alertbuffer_storage_volume_size | default('10Gi') }}"
openshift_prometheus_alertbuffer_pvc_access_modes: [ReadWriteOnce]
openshift_prometheus_alertbuffer_pvc_pv_selector: "{{ openshift_prometheus_alertbuffer_storage_labels | default({}) }}"
openshift_prometheus_alertbuffer_sc_name: "{{ openshift_prometheus_alertbuffer_storage_class | default(None) }}"

# container resources
openshift_prometheus_cpu_limit: null
openshift_prometheus_memory_limit: null
openshift_prometheus_cpu_requests: null
openshift_prometheus_memory_requests: null
openshift_prometheus_alertmanager_cpu_limit: null
openshift_prometheus_alertmanager_memory_limit: null
openshift_prometheus_alertmanager_cpu_requests: null
openshift_prometheus_alertmanager_memory_requests: null
openshift_prometheus_alertbuffer_cpu_limit: null
openshift_prometheus_alertbuffer_memory_limit: null
openshift_prometheus_alertbuffer_cpu_requests: null
openshift_prometheus_alertbuffer_memory_requests: null
openshift_prometheus_oauth_proxy_cpu_limit: null
openshift_prometheus_oauth_proxy_memory_limit: null
openshift_prometheus_oauth_proxy_cpu_requests: null
openshift_prometheus_oauth_proxy_memory_requests: null

# Firewall settings
r_openshift_prometheus_firewall_enabled: "{{ os_firewall_enabled | default(True) }}"
r_openshift_prometheus_use_firewalld: "{{ os_firewall_use_firewalld | default(False) }}"
r_openshift_prometheus_os_firewall_deny: []
r_openshift_prometheus_os_firewall_allow:
  - service: node-exporter
    port: "9100/tcp"
    cond: "{{ openshift_prometheus_node_exporter_install | bool }}"
