---
- name: Delete OpenShift Kuryr pods prior to upgrade
  shell: >
    {{ openshift_client_binary }} get pods
    --config={{ openshift.common.config_base }}/master/admin.kubeconfig
    --field-selector=spec.nodeName={{ l_kubelet_node_name | lower }}
    -o json
    -n {{ kuryr_namespace }} |
    {{ openshift_client_binary }} delete
    --config={{ openshift.common.config_base }}/master/admin.kubeconfig
    --force
    --grace-period=0
    -f -
  delegate_to: "{{ groups.oo_first_master.0 }}"
